version: 2
updates:
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      flake-inputs:
        patterns:
          - "*"
    commit-message:
      prefix: "flake"
    open-pull-requests-limit: 1
